var dictionary = [
        { term: "3D printing", definition: "Percetakan 3D" },
        { term: "4K resolution", definition: "Resolusi 4K" },
        { term: "Access control", definition: "Kontrol akses" },
        { term: "Adaptive software", definition: "Perangkat lunak adaptif" },
        { term: "Adware", definition: "Perangkat lunak iklan" },
        { term: "Algorithm", definition: "Algoritma" },
        { term: "Algorithmic trading", definition: "Perdagangan algoritmik" },
        { term: "Ambient computing", definition: "Komputasi ambiens" },
        { term: "Analog", definition: "Analog" },
        { term: "Animation", definition: "Animasi" },
        { term: "Anonymizer", definition: "Anonimiser" },
        { term: "Antivirus", definition: "Antivirus" },
        { term: "API (Application Programming Interface)", definition: "API (Antarmuka Pemrograman Aplikasi)" },
        { term: "App", definition: "Aplikasi" },
        { term: "Application", definition: "Aplikasi" },
        { term: "Archiving", definition: "Pengarsipan" },
        { term: "ARP (Address Resolution Protocol)", definition: "ARP (Protokol Resolusi Alamat)" },
        { term: "Artificial Intelligence (AI)", definition: "Kecerdasan Buatan (AI)" },
        { term: "Augmented Reality (AR)", definition: "Realitas Tertambah (AR)" },
        { term: "Authentication", definition: "Otentikasi" },
        { term: "Authentication token", definition: "Token otentikasi" },
        { term: "Autoresponder", definition: "Autoresponder" },
        { term: "Avatar", definition: "Avatar" },
        { term: "Backend", definition: "Backend" },
        { term: "Bandwidth", definition: "Lebar pita" },
        { term: "Bandwidth throttling", definition: "Penyesuaian lebar pita" },
        { term: "Base64", definition: "Basis64" },
        { term: "Benchmark", definition: "Tolak ukur" },
        { term: "Big Data", definition: "Data besar" },
        { term: "Binary", definition: "Biner" },
        { term: "Binary tree", definition: "Pohon biner" },
        { term: "BIOS", definition: "BIOS" },
        { term: "BIOS update", definition: "Pembaruan BIOS" },
        { term: "Bit", definition: "Bit" },
        { term: "Bit rate", definition: "Laju bit" },
        { term: "Bitmap", definition: "Bitmap" },
        { term: "Black hat", definition: "Topi hitam" },
        { term: "Blockchain", definition: "Rantai blok" },
        { term: "Bluetooth", definition: "Bluetooth" },
        { term: "Bluetooth LE (Low Energy)", definition: "Bluetooth LE (Energi Rendah)" },
        { term: "Bookmark", definition: "Tandai" },
        { term: "Boolean", definition: "Boolean" },
        { term: "Bot", definition: "Bot" },
        { term: "Bootstrap", definition: "Bootstrap" },
        { term: "Brute force", definition: "Paksaan kasar" },
        { term: "Buffer", definition: "Buffer" },
        { term: "Buffer overflow", definition: "Tumpah buffer" },
        { term: "Bug", definition: "Bug" },
        { term: "Buggy", definition: "Kecelakaan" },
        { term: "Build automation", definition: "Automatisasi pembangunan" },
        { term: "Burn", definition: "Bakar" },
        { term: "Bus", definition: "Bus" },
        { term: "Byte", definition: "Byte" },
        { term: "Cache", definition: "Cache" },
        { term: "Call stack", definition: "Tumpukan panggilan" },
        { term: "Camera", definition: "Kamera" },
        { term: "Capture", definition: "Penangkapan" },
        { term: "Case sensitive", definition: "Peka huruf besar-kecil" },
        { term: "CD (Compact Disc)", definition: "CD (Compact Disc)" },
        { term: "CD-ROM", definition: "CD-ROM" },
        { term: "Cellular network", definition: "Jaringan seluler" },
        { term: "Chatbot", definition: "Chatbot" },
        { term: "Checksum", definition: "Checksum" },
        { term: "Chrome", definition: "Chrome" },
        { term: "Circuit", definition: "Sirkuit" },
        { term: "Client", definition: "Klien" },
        { term: "Cloud computing", definition: "Komputasi awan" },
        { term: "Cluster", definition: "Klaster" },
        { term: "Codec", definition: "Codec" },
        { term: "Command", definition: "Perintah" },
        { term: "Command-line interface (CLI)", definition: "Antarmuka baris perintah (CLI)" },
        { term: "Compiler", definition: "Compiler" },
        { term: "Computer", definition: "Komputer" },
        { term: "Computer-aided design (CAD)", definition: "Desain berbantu komputer (CAD)" },
        { term: "Computer virus", definition: "Virus komputer" },
        { term: "Concatenate", definition: "Konkatenasi" },
        { term: "Cookie", definition: "Cookie" },
        { term: "Copy", definition: "Salin" },
        { term: "Cracker", definition: "Pengganggu" },
        { term: "Crash", definition: "Crash" },
        { term: "Creative Commons", definition: "Creative Commons" },
        { term: "Credential", definition: "Kredensial" },
        { term: "Crumb trail", definition: "Jejak remah" },
        { term: "Cryptocurrency", definition: "Kriptokurensi" },
        { term: "CSS (Cascading Style Sheets)", definition: "CSS (Cascading Style Sheets)" },
        { term: "Cursor", definition: "Kursor" },
        { term: "Cyberattack", definition: "Serangan siber" },
        { term: "Cyberbullying", definition: "Penggertakan siber" },
        { term: "Cybercrime", definition: "Kejahatan siber" },
        { term: "Cybersecurity", definition: "Keamanan siber" },
        { term: "Cyberspace", definition: "Siber" },
        { term: "Daemon", definition: "Daemon" },
        { term: "Data", definition: "Data" },
        { term: "Data center", definition: "Pusat data" },
        { term: "Data compression", definition: "Kompresi data" },
        { term: "Data mining", definition: "Penggalian data" },
        { term: "Data recovery", definition: "Pemulihan data" },
        { term: "Data science", definition: "Ilmu data" },
        { term: "Data structure", definition: "Struktur data" },
        { term: "Data type", definition: "Jenis data" },
        { term: "Database", definition: "Basis data" },
        { term: "DBMS (Database Management System)", definition: "DBMS (Sistem Manajemen Basis Data)" },
        { term: "Debug", definition: "Debug" },
        { term: "Debugger", definition: "Debugger" },
        { term: "Decryption", definition: "Dekripsi" },
        { term: "Deep learning", definition: "Pembelajaran mendalam" },
        { term: "Default", definition: "Default" },
        { term: "Defragmentation", definition: "Defragmentasi" },
        { term: "Delete", definition: "Hapus" },
        { term: "Denial of Service (DoS)", definition: "Penolakan Layanan (DoS)" },
        { term: "Desktop", definition: "Desktop" },
        { term: "Desktop publishing", definition: "Penerbitan desktop" },
        { term: "Developer", definition: "Pengembang" },
        { term: "DHCP (Dynamic Host Configuration Protocol)", definition: "DHCP (Protokol Konfigurasi Host Dinamis)" },
        { term: "Digital", definition: "Digital" },
        { term: "Digital divide", definition: "Pembagian digital" },
        { term: "Digital footprint", definition: "Jejak digital" },
        { term: "Digital signature", definition: "Tanda tangan digital" },
        { term: "Directory", definition: "Direktori" },
        { term: "Disaster recovery", definition: "Pemulihan bencana" },
        { term: "Disk", definition: "Disk" },
        { term: "Disk image", definition: "Gambar disk" },
        { term: "Disk partition", definition: "Partisi disk" },
        { term: "Display", definition: "Tampilan" },
        { term: "Disruptive technology", definition: "Teknologi yang mengganggu" },
        { term: "Distributed computing", definition: "Komputasi terdistribusi" },
        { term: "Dithering", definition: "Dithering" },
        { term: "Domain", definition: "Domain" },
        { term: "Domain name", definition: "Nama domain" },
        { term: "Download", definition: "Unduh" },
        { term: "DRAM (Dynamic Random Access Memory)", definition: "DRAM (Memori Akses Acak Dinamis)" },
        { term: "Driver", definition: "Driver" },
        { term: "Drop-down list", definition: "Daftar drop-down" },
        { term: "DSL (Digital Subscriber Line)", definition: "DSL (Digital Subscriber Line)" },
        { term: "DVD (Digital Versatile Disc)", definition: "DVD (Digital Versatile Disc)" },
        { term: "Dynamic", definition: "Dinamis" },
        { term: "E-commerce", definition: "E-commerce" },
        { term: "Ebook", definition: "Ebook" },
        { term: "ECC (Error Correcting Code)", definition: "ECC (Kode Koreksi Kesalahan)" },
        { term: "Edge computing", definition: "Komputasi tepi" },
        { term: "Editor", definition: "Editor" },
        { term: "EDR (Endpoint Detection and Response)", definition: "EDR (Deteksi dan Respons Ujung)" },
        { term: "EFS (Encrypting File System)", definition: "EFS (Sistem Berkas Enkripsi)" },
        { term: "Email", definition: "Email" },
        { term: "Emoticon", definition: "Emotikon" },
        { term: "Encryption", definition: "Enkripsi" },
        { term: "End-user", definition: "Pengguna akhir" },
        { term: "Endpoint", definition: "Ujung" },
        { term: "Energy efficiency", definition: "Efisiensi energi" },
        { term: "Energy star", definition: "Bintang energi" },
        { term: "Engineering", definition: "Teknik" },
        { term: "Enrollment", definition: "Pendaftaran" },
        { term: "Enterprise", definition: "Perusahaan" },
        { term: "Enterprise resource planning (ERP)", definition: "Perencanaan sumber daya perusahaan (ERP)" },
        { term: "Entity", definition: "Entitas" },
        { term: "Environment", definition: "Lingkungan" },
        { term: "EPROM (Erasable Programmable Read-Only Memory)", definition: "EPROM (Memori Baca-Tulis Terprogram yang Dapat Dihapus)" },
        { term: "Error", definition: "Kesalahan" },
        { term: "Ethernet", definition: "Ethernet" },
        { term: "Evil twin", definition: "Kembar jahat" },
        { term: "Executable file", definition: "Berkas yang dapat dieksekusi" },
        { term: "Exit", definition: "Keluar" },
        { term: "Exploit", definition: "Eksploitasi" },
        { term: "Extension", definition: "Ekstensi" },
        { term: "Extranet", definition: "Extranet" },
        { term: "FAT (File Allocation Table)", definition: "FAT (Tabel Penugasan Berkas)" },
        { term: "Fault tolerance", definition: "Toleransi kesalahan" },
        { term: "Favicon", definition: "Favicon" },
        { term: "Fiber optic", definition: "Serat optik" },
        { term: "File", definition: "Berkas" },
        { term: "File format", definition: "Format berkas" },
        { term: "File server", definition: "Server berkas" },
        { term: "Filename", definition: "Nama berkas" },
        { term: "Firewall", definition: "Firewall" },
        { term: "Firmware", definition: "Firmware" },
        { term: "Flash drive", definition: "Flash drive" },
        { term: "Flash memory", definition: "Memori flash" },
        { term: "Floppy disk", definition: "Disket" },
        { term: "Flowchart", definition: "Diagram alir" },
        { term: "Folder", definition: "Folder" },
        { term: "Font", definition: "Font" },
        { term: "Footprint", definition: "Jejak" },
        { term: "Form", definition: "Formulir" },
        { term: "Format", definition: "Format" },
        { term: "Formula", definition: "Formula" },
        { term: "Forum", definition: "Forum" },
        { term: "Framework", definition: "Kerangka kerja" },
        { term: "Freeware", definition: "Freeware" },
        { term: "FTP (File Transfer Protocol)", definition: "FTP (Protokol Transfer Berkas)" },
        { term: "Function", definition: "Fungsi" },
        { term: "Gaming", definition: "Bermain game" },
        { term: "Gateway", definition: "Gerbang" },
        { term: "GIF (Graphics Interchange Format)", definition: "GIF (Format Pertukaran Grafis)" },
        { term: "Gigabyte", definition: "Gigabyte" },
        { term: "GIS (Geographic Information System)", definition: "GIS (Sistem Informasi Geografis)" },
        { term: "GitHub", definition: "GitHub" },
        { term: "GPS (Global Positioning System)", definition: "GPS (Sistem Pemosisian Global)" },
        { term: "GPU (Graphics Processing Unit)", definition: "GPU (Unit Pemrosesan Grafis)" },
        { term: "Grammar checker", definition: "Pemeriksa tata bahasa" },
        { term: "Graphics", definition: "Grafis" },
        { term: "Graphical user interface (GUI)", definition: "Antarmuka pengguna grafis (GUI)" },
        { term: "Grid computing", definition: "Komputasi grid" },
        { term: "Groupware", definition: "Groupware" },
        { term: "GUI (Graphical User Interface)", definition: "GUI (Antarmuka Pengguna Grafis)" },
        { term: "Hacker", definition: "Peretas" },
        { term: "Hard drive", definition: "Hard drive" },
        { term: "Hardware", definition: "Perangkat keras" },
        { term: "Hash", definition: "Hash" },
        { term: "HDMI (High-Definition Multimedia Interface)", definition: "HDMI (Antarmuka Multimedia Definisi Tinggi)" },
        { term: "Header", definition: "Header" },
        { term: "Heap", definition: "Tumpukan" },
        { term: "Helpdesk", definition: "Helpdesk" },
        { term: "Hibernate", definition: "Hibernasi" },
        { term: "Home page", definition: "Halaman utama" },
        { term: "Host", definition: "Host" },
        { term: "Hotspot", definition: "Hotspot" },
        { term: "HTML (Hypertext Markup Language)", definition: "HTML (Bahasa Pemformatan Hiperteks)" },
        { term: "HTTP (Hypertext Transfer Protocol)", definition: "HTTP (Protokol Transfer Hiperteks)" },
        { term: "HTTPS (Hypertext Transfer Protocol Secure)", definition: "HTTPS (Protokol Transfer Hiperteks Aman)" },
        { term: "Hub", definition: "Hub" },
        { term: "Hybrid", definition: "Hibrida" },
        { term: "Hyperlink", definition: "Hyperlink" },
        { term: "Hypertext", definition: "Hiperteks" },
        { term: "Icon", definition: "Ikon" },
        { term: "IDE (Integrated Development Environment)", definition: "IDE ( Lingkungan Pengembangan Terpadu)" },
        { term: "Identity theft", definition: "Pencurian identitas" },
        { term: "Image", definition: "Gambar" },
        { term: "IMAP (Internet Message Access Protocol)", definition: "IMAP (Protokol Akses Pesan Internet)" },
        { term: "Impact printer", definition: "Printer dampak" },
        { term: "Implementation", definition: "Implementasi" },
        { term: "Input", definition: "Input" },
        { term: "Input device", definition: "Perangkat masukan" },
        { term: "Installation", definition: "Pemasangan" },
        { term: "Instant messaging", definition: "Pesan instan" },
        { term: "Integer", definition: "Integer" },
        { term: "Integrated circuit", definition: "Sirkuit terpadu" },
        { term: "Integration", definition: "Integrasi" },
        { term: "Interface", definition: "Antarmuka" },
        { term: "Internet", definition: "Internet" },
        { term: "Internet Explorer", definition: "Internet Explorer" },
        { term: "Internet of Things (IoT)", definition: "Internet of Things (IoT)" },
        { term: "Internet service provider (ISP)", definition: "Penyedia layanan internet (ISP)" },
        { term: "Interoperability", definition: "Interoperabilitas" },
        { term: "Interpreter", definition: "Penerjemah" },
        { term: "Intranet", definition: "Intranet" },
        { term: "IP address (Internet Protocol address)", definition: "Alamat IP (Alamat Protokol Internet)" },
        { term: "IP telephony", definition: "Telepon IP" },
        { term: "ISDN (Integrated Services Digital Network)", definition: "ISDN (Jaringan Digital Layanan Terpadu)" },
        { term: "ISP (Internet Service Provider)", definition: "ISP (Penyedia Layanan Internet)" },
        { term: "Iterate", definition: "Iterasi" },
        { term: "IT (Information Technology)", definition: "IT (Teknologi Informasi)" },
        { term: "Jabber", definition: "Jabber" },
        { term: "Java", definition: "Java" },
        { term: "JavaScript", definition: "JavaScript" },
        { term: "Joystick", definition: "Joystick" },
        { term: "JPEG (Joint Photographic Experts Group)", definition: "JPEG (Kelompok Ahli Fotografi Bersama)" },
        { term: "JSON (JavaScript Object Notation)", definition: "JSON (Notasi Objek JavaScript)" },
        { term: "JSP (JavaServer Pages)", definition: "JSP (JavaServer Pages)" },
        { term: "Kbps (Kilobits per second)", definition: "Kbps (Kilobit per detik)" },
        { term: "Keyboard", definition: "Keyboard" },
        { term: "Keylogger", definition: "Perekam ketikan" },
        { term: "Keyword", definition: "Kata kunci" },
        { term: "Kiosk", definition: "Kios" },
        { term: "LAN (Local Area Network)", definition: "LAN (Jaringan Area Lokal)" },
        { term: "Latency", definition: "Latensi" },
        { term: "LCD (Liquid Crystal Display)", definition: "LCD (Tampilan Kristal Cair)" },
        { term: "LED (Light Emitting Diode)", definition: "LED (Dioda Penyala)" },
        { term: "Library", definition: "Perpustakaan" },
        { term: "License", definition: "Lisensi" },
        { term: "Lifecycle", definition: "Siklus hidup" },
        { term: "Lightning port", definition: "Port lightning" },
        { term: "Link", definition: "Tautan" },
        { term: "Linux", definition: "Linux" },
        { term: "List", definition: "Daftar" },
        { term: "Localhost", definition: "Localhost" },
        { term: "Lockdown", definition: "Pembatasan" },
        { term: "Logic", definition: "Logika" },
        { term: "Login", definition: "Masuk" },
        { term: "Logout", definition: "Keluar" },
        { term: "Loop", definition: "Loop" },
        { term: "Lossless compression", definition: "Kompresi tanpa kehilangan" },
        { term: "Lossy compression", definition: "Kompresi berkurang" },
        { term: "Machine learning", definition: "Pembelajaran mesin" },
        { term: "Macro", definition: "Makro" },
        { term: "Mainframe", definition: "Mainframe" },
        { term: "Malware", definition: "Malware" },
        { term: "Mapper", definition: "Pemeta" },
        { term: "Markup", definition: "Markup" },
        { term: "Mashup", definition: "Mashup" },
        { term: "Megabyte", definition: "Megabyte" },
        { term: "Memory", definition: "Memori" },
        { term: "Menu", definition: "Menu" },
        { term: "Metadata", definition: "Metadata" },
        { term: "Metered connection", definition: "Koneksi yang dihitung" },
        { term: "Microblog", definition: "Microblog" },
        { term: "Microcontroller", definition: "Microcontroller" },
        { term: "Microphone", definition: "Mikrofon" },
        { term: "Middleware", definition: "Middleware" },
        { term: "Migration", definition: "Migrasi" },
        { term: "Millisecond", definition: "Milidetik" },
        { term: "Minicomputer", definition: "Minikomputer" },
        { term: "Mirror", definition: "Cermin" },
        { term: "MIT (Massachusetts Institute of Technology)", definition: "MIT (Institut Teknologi Massachusetts)" },
        { term: "Mobile", definition: "Seluler" },
        { term: "Modem", definition: "Modem" },
        { term: "Monitor", definition: "Monitor" },
        { term: "Motherboard", definition: "Motherboard" },
        { term: "Mouse", definition: "Mouse" },
        { term: "MP3", definition: "MP3" },
        { term: "MP4", definition: "MP4" },
        { term: "Multimedia", definition: "Multimedia" },
        { term: "Multitasking", definition: "Multitasking" },
        { term: "Nanotechnology", definition: "Nanoteknologi" },
        { term: "NAS (Network Attached Storage)", definition: "NAS (Penyimpanan Terpasang Jaringan)" },
        { term: "Navigation", definition: "Navigasi" },
        { term: "Netiquette", definition: "Netiket" },
        { term: "Network", definition: "Jaringan" },
        { term: "Network adapter", definition: "Adaptor jaringan" },
        { term: "Network card", definition: "Kartu jaringan" },
        { term: "Network drive", definition: "Drive jaringan" },
        { term: "Network interface card (NIC)", definition: "Kartu antarmuka jaringan (NIC)" },
        { term: "Network security", definition: "Keamanan jaringan" },
        { term: "Network topology", definition: "Topologi jaringan" },
        { term: "Newsgroup", definition: "Kelompok berita" },
        { term: "Node", definition: "Node" },
        { term: "Node.js", definition: "Node.js" },
        { term: "Noise-canceling", definition: "Pembatal kebisingan" },
        { term: "Nonvolatile memory", definition: "Memori non-volatil" },
        { term: "Notebook", definition: "Notebook" },
        { term: "Notification", definition: "Pemberitahuan" },
        { term: "Null", definition: "Nol" },
        { term: "Numeric", definition: "Numerik" },
        { term: "OCR (Optical Character Recognition)", definition: "OCR (Pengenalan Karakter Optik)" },
        { term: "OEM (Original Equipment Manufacturer)", definition: "OEM (Pabrikan Peralatan Asli)" },
        { term: "Offline", definition: "Luar jaringan" },
        { term: "Online", definition: "Daring" },
        { term: "Open source", definition: "Sumber terbuka" },
        { term: "Operating system (OS)", definition: "Sistem operasi (OS)" },
        { term: "Optical character recognition (OCR)", definition: "Pengenalan karakter optik (OCR)" },
        { term: "Optimize", definition: "Optimalkan" },
        { term: "Oracle", definition: "Oracle" },
        { term: "OS (Operating System)", definition: "OS (Sistem Operasi)" },
        { term: "Output", definition: "Output" },
        { term: "Output device", definition: "Perangkat keluaran" },
        { term: "Packet", definition: "Paket" },
        { term: "Packet sniffing", definition: "Pengendus paket" },
        { term: "Page", definition: "Halaman" },
        { term: "Page layout", definition: "Tata letak halaman" },
        { term: "Page rank", definition: "Peringkat halaman" },
        { term: "Parallel computing", definition: "Komputasi paralel" },
        { term: "Parameter", definition: "Parameter" },
        { term: "Parent directory", definition: "Direktori induk" },
        { term: "Partition", definition: "Partisi" },
        { term: "Password", definition: "Kata sandi" },
        { term: "Paste", definition: "Tempel" },
        { term: "Patch", definition: "Perbaikan" },
        { term: "Path", definition: "Jalur" },
        { term: "Pattern", definition: "Pola" },
        { term: "Payload", definition: "Muatan" },
        { term: "PDF (Portable Document Format)", definition: "PDF (Format Dokumen Portabel)" },
        { term: "Pen drive", definition: "Pen drive" },
        { term: "Peripheral", definition: "Peripheral" },
        { term: "Perl", definition: "Perl" },
        { term: "Personal computer (PC)", definition: "Komputer pribadi (PC)" },
        { term: "Personal data assistant (PDA)", definition: "Asisten data pribadi (PDA)" },
        { term: "Pharming", definition: "Pharming" },
        { term: "Phishing", definition: "Phishing" },
        { term: "PHP (Hypertext Preprocessor)", definition: "PHP (Hypertext Preprocessor)" },
        { term: "Piconet", definition: "Piconet" },
        { term: "Ping", definition: "Ping" },
        { term: "Pixel", definition: "Pixel" },
        { term: "Plagiarism", definition: "Plagiarisme" },
        { term: "Platform", definition: "Platform" },
        { term: "Plug-in", definition: "Plug-in" },
        { term: "PNG (Portable Network Graphics)", definition: "PNG (Grafik Jaringan Portabel)" },
        { term: "Podcast", definition: "Podcast" },
        { term: "Poisoning", definition: "Pencemaran" },
        { term: "Popup", definition: "Popup" },
        { term: "Portal", definition: "Portal" },
        { term: "Port scanner", definition: "Pemindai port" },
        { term: "Post", definition: "Pos" },
        { term: "Power management", definition: "Manajemen daya" },
        { term: "PPP (Point-to-Point Protocol)", definition: "PPP (Protokol Titik ke Titik)" },
        { term: "Predictive text", definition: "Teks prediktif" },
        { term: "Presentation", definition: "Presentasi" },
        { term: "Printer", definition: "Printer" },
        { term: "Private key", definition: "Kunci pribadi" },
        { term: "Processor", definition: "Prosesor" },
        { term: "Productivity software", definition: "Perangkat lunak produktivitas" },
        { term: "Program", definition: "Program" },
        { term: "Programming", definition: "Pemrograman" },
        { term: "Programming language", definition: "Bahasa pemrograman" },
        { term: "Protocol", definition: "Protokol" },
        { term: "Proxy server", definition: "Server proxy" },
        { term: "Pulse code modulation (PCM)", definition: "Modulasi kode pulsa (PCM)" },
        { term: "Python", definition: "Python" },
        { term: "QWERTY keyboard", definition: "Papan ketik QWERTY" },
        { term: "RAID (Redundant Array of Independent Disks)", definition: "RAID (Kumpulan Disk Independen yang Redundan)" },
        { term: "RAM (Random Access Memory)", definition: "RAM (Memori Akses Acak)" },
        { term: "Raster graphics", definition: "Grafis raster" },
        { term: "RDBMS (Relational Database Management System)", definition: "RDBMS (Sistem Manajemen Basis Data Relasional)" },
        { term: "Read-only memory (ROM)", definition: "Memori hanya baca (ROM)" },
        { term: "Reboot", definition: "Reboot" },
        { term: "Recovery", definition: "Pemulihan" },
        { term: "Redundancy", definition: "Redundansi" },
        { term: "Redundant", definition: "Redundan" },
        { term: "Refactoring", definition: "Refaktoring" },
        { term: "Referral", definition: "Rujukan" },
        { term: "Refurbished", definition: "Refurbished" },
        { term: "Regression testing", definition: "Pengujian regresi" },
        { term: "Registry", definition: "Registri" },
        { term: "Relational database", definition: "Basis data relasional" },
        { term: "Reliability", definition: "Keandalan" },
        { term: "Rendering", definition: "Rendering" },
        { term: "Repair", definition: "Perbaikan" },
        { term: "Repository", definition: "Repositori" },
        { term: "Request", definition: "Permintaan" },
        { term: "Reset", definition: "Reset" },
        { term: "Resolution", definition: "Resolusi" },
        { term: "Response", definition: "Tanggapan" },
        { term: "Responsive design", definition: "Desain responsif" },
        { term: "Restore", definition: "Pulihkan" },
        { term: "RFID (Radio-Frequency Identification)", definition: "RFID (Identifikasi Frekuensi Radio)" },
        { term: "RIP (Raster Image Processor)", definition: "RIP (Pemroses Gambar Raster)" },
        { term: "Robot", definition: "Robot" },
        { term: "Robotics", definition: "Robotika" },
        { term: "Root", definition: "Akar" },
        { term: "Router", definition: "Router" },
        { term: "Row", definition: "Baris" },
        { term: "RPM (Revolutions per minute)", definition: "RPM (Putaran per menit)" },
        { term: "RSS (Rich Site Summary)", definition: "RSS (Ringkasan Situs Kaya)" },
        { term: "RTF (Rich Text Format)", definition: "RTF (Format Teks Kaya)" },
        { term: "Runtime", definition: "Runtime" },
        { term: "SaaS (Software as a Service)", definition: "SaaS (Perangkat Lunak sebagai Layanan)" },
        { term: "Safari", definition: "Safari" },
        { term: "Safety", definition: "Keamanan" },
        { term: "SAN (Storage Area Network)", definition: "SAN (Jaringan Area Penyimpanan)" },
        { term: "Scalability", definition: "Scalability" },
        { term: "Scanner", definition: "Pemindai" },
        { term: "Scanning", definition: "Pemindaian" },
        { term: "Scareware", definition: "Scareware" },
        { term: "SCSI (Small Computer System Interface)", definition: "SCSI (Antarmuka Sistem Komputer Kecil)" },
        { term: "Script", definition: "Skrip" },
        { term: "Scrum", definition: "Scrum" },
        { term: "SDK (Software Development Kit)", definition: "SDK (Paket Pengembangan Perangkat Lunak)" },
        { term: "Search engine", definition: "Mesin pencari" },
        { term: "Search engine optimization (SEO)", definition: "Optimisasi mesin pencari (SEO)" },
        { term: "Secure", definition: "Aman" },
        { term: "Security", definition: "Keamanan" },
        { term: "Security token", definition: "Token keamanan" },
        { term: "Segment", definition: "Segmen" },
        { term: "Selfie", definition: "Selfie" },
        { term: "Semantic web", definition: "Web semantik" },
        { term: "Semaphore", definition: "Semafor" },
        { term: "Sensor", definition: "Sensor" },
        { term: "SEO (Search Engine Optimization)", definition: "SEO (Optimisasi Mesin Pencari)" },
        { term: "Server", definition: "Server" },
        { term: "Servlet", definition: "Servlet" },
        { term: "Session", definition: "Sesi" },
        { term: "Shareware", definition: "Shareware" },
        { term: "Shell", definition: "Shell" },
        { term: "Shift", definition: "Shift" },
        { term: "Shopping cart", definition: "Troli belanja" },
        { term: "Shortcut", definition: "Jalan pintas" },
        { term: "Sidebar", definition: "Sidebar" },
        { term: "Signal", definition: "Sinyal" },
        { term: "Signature", definition: "Tanda tangan" },
        { term: "SIM card (Subscriber Identity Module card)", definition: "Kartu SIM (Kartu Modul Identitas Pelanggan)" },
        { term: "Simulation", definition: "Simulasi" },
        { term: "Skype", definition: "Skype" },
        { term: "Slack", definition: "Slack" },
        { term: "Slashdot effect", definition: "Efek Slashdot" },
        { term: "Slideshow", definition: "Slideshow" },
        { term: "Smartphone", definition: "Ponsel pintar" },
        { term: "SMTP (Simple Mail Transfer Protocol)", definition: "SMTP (Protokol Transfer Surat Elektronik Sederhana)" },
        { term: "Snapchat", definition: "Snapchat" },
        { term: "Sniffer", definition: "Pengendus" },
        { term: "Social engineering", definition: "Teknik sosial" },
        { term: "Social media", definition: "Media sosial" },
        { term: "Socket", definition: "Socket" },
        { term: "Software", definition: "Perangkat lunak" },
        { term: "Software development", definition: "Pengembangan perangkat lunak" },
        { term: "Software engineer", definition: "Insinyur perangkat lunak" },
        { term: "Software piracy", definition: "Pembajakan perangkat lunak" },
        { term: "Software update", definition: "Pembaruan perangkat lunak" },
        { term: "Solution", definition: "Solusi" },
        { term: "Sound card", definition: "Kartu suara" },
        { term: "Spam", definition: "Spam" },
        { term: "Speaker", definition: "Pengeras suara" },
        { term: "Spooling", definition: "Spooling" },
        { term: "Spreadsheet", definition: "Lembar kerja" },
        { term: "SQL (Structured Query Language)", definition: "SQL (Bahasa Permintaan Terstruktur)" },
        { term: "SQL injection", definition: "Injeksi SQL" },
        { term: "SSL (Secure Sockets Layer)", definition: "SSL (Lapisan Soket Aman)" },
        { term: "Stack", definition: "Tumpukan" },
        { term: "Star topology", definition: "Topologi bintang" },
        { term: "Startup", definition: "Startup" },
        { term: "Storage", definition: "Penyimpanan" },
        { term: "Storage area network (SAN)", definition: "Jaringan area penyimpanan (SAN)" },
        { term: "Streaming", definition: "Streaming" },
        { term: "Structured programming", definition: "Pemrograman terstruktur" },
        { term: "Style sheet", definition: "Lembar gaya" },
        { term: "Subnet", definition: "Subnet" },
        { term: "Subroutine", definition: "Subrutin" },
        { term: "Subscript", definition: "Subskrip" },
        { term: "Subsystem", definition: "Subsistem" },
        { term: "Substitute", definition: "Ganti" },
        { term: "Suffix", definition: "Sufiks" },
        { term: "Supercomputer", definition: "Superkomputer" },
        { term: "Superscript", definition: "Superskrip" },
        { term: "Supply chain management (SCM)", definition: "Manajemen rantai pasokan (SCM)" },
        { term: "Surge protector", definition: "Pelindung lonjakan" },
        { term: "Surveillance", definition: "Survei" },
        { term: "SVG (Scalable Vector Graphics)", definition: "SVG (Grafis Vektor Skalabel)" },
        { term: "Switch", definition: "Switch" },
        { term: "Symbol", definition: "Simbol" },
        { term: "Synchronization", definition: "Sinkronisasi" },
        { term: "Syntax", definition: "Sintaksis" },
        { term: "System", definition: "Sistem" },
        { term: "System administrator", definition: "Administrator sistem" },
        { term: "System analyst", definition: "Analis sistem" },
        { term: "System clock", definition: "Jam sistem" },
        { term: "System software", definition: "Perangkat lunak sistem" },
        { term: "Table", definition: "Tabel" },
        { term: "Tablet", definition: "Tablet" },
        { term: "Tag", definition: "Tag" },
        { term: "TCP/IP (Transmission Control Protocol/Internet Protocol)", definition: "TCP/IP (Protokol Kontrol Transmisi/Protokol Internet)" },
        { term: "Template", definition: "Template" },
        { term: "Terabyte", definition: "Terabyte" },
        { term: "Terminal", definition: "Terminal" },
        { term: "Terminator", definition: "Terminator" },
        { term: "Text", definition: "Teks" },
        { term: "Text editor", definition: "Editor teks" },
        { term: "Text messaging", definition: "Pesan teks" },
        { term: "Texture mapping", definition: "Pemetaan tekstur" },
        { term: "Thermal printer", definition: "Printer termal" },
        { term: "Thread", definition: "Utas" },
        { term: "Thumbnail", definition: "Gambar kecil" },
        { term: "TIFF (Tagged Image File Format)", definition: "TIFF (Format Berkas Gambar Berlabel)" },
        { term: "Time-sharing", definition: "Pemakaian waktu" },
        { term: "Toolbar", definition: "Toolbar" },
        { term: "Topology", definition: "Topologi" },
        { term: "Torrent", definition: "Torrent" },
        { term: "Touchpad", definition: "Touchpad" },
        { term: "Trackball", definition: "Trackball" },
        { term: "Tracker", definition: "Pelacak" },
        { term: "Trademark", definition: "Merek dagang" },
        { term: "Traffic", definition: "Lalu lintas" },
        { term: "Training", definition: "Pelatihan" },
        { term: "Transaction", definition: "Transaksi" },
        { term: "Transmission", definition: "Transmisi" },
        { term: "Transmitter", definition: "Pengirim" },
        { term: "Trojan horse", definition: "Kuda Troya" },
        { term: "Troubleshooting", definition: "Pemecahan masalah" },
        { term: "Tumblr", definition: "Tumblr" },
        { term: "Twitter", definition: "Twitter" },
        { term: "Typeface", definition: "Huruf" },
        { term: "Ubuntu", definition: "Ubuntu" },
        { term: "UDP (User Datagram Protocol)", definition: "UDP (Protokol Datagram Pengguna)" },
        { term: "UI (User Interface)", definition: "UI (Antarmuka Pengguna)" },
        { term: "Ultra HD", definition: "Ultra HD" },
        { term: "UML (Unified Modeling Language)", definition: "UML (Bahasa Pemodelan Terpadu)" },
        { term: "Unicode", definition: "Unicode" },
        { term: "Unix", definition: "Unix" },
        { term: "Upload", definition: "Unggah" },
        { term: "UPS (Uninterruptible Power Supply)", definition: "UPS (Sumber Daya Listrik Tak Terputus)" },
        { term: "URL (Uniform Resource Locator)", definition: "URL (Locator Sumber Daya Seragam)" },
        { term: "USB (Universal Serial Bus)", definition: "USB (Bus Seri Universal)" },
        { term: "User", definition: "Pengguna" },
        { term: "Username", definition: "Nama pengguna" },
        { term: "Utility software", definition: "Perangkat lunak utilitas" },
        { term: "UTF-8 (Unicode Transformation Format 8-bit)", definition: "UTF-8 (Format Transformasi Unicode 8-bit)" },
        { term: "Validation", definition: "Validasi" },
        { term: "VGA (Video Graphics Array)", definition: "VGA (Susunan Grafis Video)" },
        { term: "Virus", definition: "Virus" },
        { term: "Virtual", definition: "Virtual" },
        { term: "Virtual memory", definition: "Memori virtual" },
        { term: "Virtual private network (VPN)", definition: "Jaringan pribadi virtual (VPN)" },
        { term: "Virtual reality (VR)", definition: "Realitas virtual (VR)" },
        { term: "Virus scan", definition: "Pemindaian virus" },
        { term: "Visual Basic", definition: "Visual Basic" },
        { term: "Visualization", definition: "Visualisasi" },
        { term: "VLAN (Virtual Local Area Network)", definition: "VLAN (Jaringan Area Lokal Virtual)" },
        { term: "Vlog (Video Blog)", definition: "Vlog (Blog Video)" },
        { term: "VoIP (Voice over Internet Protocol)", definition: "VoIP (Panggilan suara via Internet)" },
        { term: "Vulnerability", definition: "Kerentanan" },
        { term: "W3C (World Wide Web Consortium)", definition: "W3C (Konsorsium World Wide Web)" },
        { term: "WAN (Wide Area Network)", definition: "WAN (Jaringan Luas)" },
        { term: "WAP (Wireless Application Protocol)", definition: "WAP (Protokol Aplikasi Nirkabel)" },
        { term: "Warez", definition: "Warez" },
        { term: "Warm boot", definition: "Pemanasan boot" },
        { term: "WAV (Waveform Audio File Format)", definition: "WAV (Format Berkas Audio Gelombang)" },
        { term: "Web 2.0", definition: "Web 2.0" },
        { term: "Web browser", definition: "Browser web" },
        { term: "Web designer", definition: "Perancang web" },
        { term: "Web development", definition: "Pengembangan web" },
        { term: "Web hosting", definition: "Hosting web" },
        { term: "Web page", definition: "Halaman web" },
        { term: "Web server", definition: "Server web" },
        { term: "Webcam", definition: "Webcam" },
        { term: "Website", definition: "Situs web" },
        { term: "Wi-Fi", definition: "Wi-Fi" },
        { term: "Wiki", definition: "Wiki" },
        { term: "Windows", definition: "Windows" },
        { term: "Windows Explorer", definition: "Windows Explorer" },
        { term: "Wired", definition: "Kabel" },
        { term: "Wireless", definition: "Nirkabel" },
        { term: "Word processor", definition: "Pemroses kata" },
        { term: "Workflow", definition: "Alur kerja" },
        { term: "Workstation", definition: "Workstation" },
        { term: "World Wide Web", definition: "World Wide Web" },
        { term: "Worm", definition: "Cacing" },
        { term: "WPA (Wi-Fi Protected Access)", definition: "WPA (Akses Terlindungi Wi-Fi)" },
        { term: "WYSIWYG (What You See Is What You Get)", definition: "WYSIWYG (Apa yang Anda Lihat Adalah Apa yang Anda Dapatkan)" },
        { term: "XML (eXtensible Markup Language)", definition: "XML (Bahasa Pemrosesan Ekstensibel)" },
        { term: "Yahoo!", definition: "Yahoo!" },
        { term: "YouTube", definition: "YouTube" },
        { term: "Zettabyte", definition: "Zettabyte" },
        { term: "ZIP", definition: "ZIP" },
        { term: "Zoom", definition: "Zoom" },
        { term: "Zombie", definition: "Zombie" }
];

// Function to render the dictionary
function renderDictionary(terms) {
    var dictionaryContainer = document.getElementById('dictionary');
    dictionaryContainer.innerHTML = '';

    terms.forEach(function(term) {
        var termElement = document.createElement('div');
        termElement.classList.add('term');

        var html = '<h3>' + term.term + '</h3>';
        html += '<p>' + term.definition + '</p>';

        termElement.innerHTML = html;
        dictionaryContainer.appendChild(termElement);
    });
}

// Initial rendering of the dictionary
renderDictionary(dictionary);

// Function to handle search
function search() {
    var searchTerm = document.getElementById('searchTerm').value.toLowerCase();
    var searchResults = dictionary.filter(function(term) {
        return term.term.toLowerCase().includes(searchTerm);
    });
    renderDictionary(searchResults);
}
